image: alpine/edge
packages:
  - nodejs
  - npm
  - chromium
  - harfbuzz
  - nss
  - docker
    # - openssh
sources:
  - https://git.sr.ht/~hokiegeek/hg-tea
environment:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  CHROME_BIN: "/usr/bin/chromium-browser"
  # IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  # IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  # SERVICE: hgtea.service
tasks:
  - setup: |
      cd hg-tea
      npm install
  - lint: |
      cd hg-tea
      npm run lint
  - build: |
      cd hg-tea
      npm run build
      version=$(awk 'BEGIN { FS=":"; RS="," } $1 ~ /"version"/ { gsub(/( |")/, "", $0); print $2 }' package.json)
      sed -i '/^<head>$/ a\    <meta name="application-name" content="hokiegeek.net_tea" data-version="'${version}${version_suffix:+":${version_suffix}"}'" />' dist/index.html
  - test: |
      cd hg-tea
      npm run test
      # - package: |
      #     cd hg-tea
      #     docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_TOKEN} ${CI_REGISTRY}
      #     docker build -t $IMAGE_TAG .
      #     docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
      #     docker push $IMAGE_TAG
      #     docker push $IMAGE_LATEST_TAG
      # - deploy: |
      #     cd hg-tea
      #     scp -o StrictHostKeyChecking=no ./prod-conf/proxy-tea.conf ./prod-conf/${SERVICE} $ADMIN_USER@${DEPLOY_HOST}:/tmp
      #     ssh -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo mkdir -p /etc/nginx/conf.d; sudo mv /tmp/proxy-tea.conf /etc/nginx/conf.d && sudo mv /tmp/${SERVICE} /etc/systemd/system/"
      #     ssh -o StrictHostKeyChecking=no $ADMIN_USER@${DEPLOY_HOST} "sudo systemctl daemon-reload && sudo systemctl enable ${SERVICE}; sudo systemctl restart hgproxy.service ${SERVICE}"
