image: node:11-alpine
environment:
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    CHROME_BIN: "/usr/bin/chromium-browser"
sources:
    - https://git.sr.ht/~hokiegeek/hg-tea
tasks:
    - setup: |
        npm install
    - lint: |
        npm run lint
    - build: |
        npm run build # Run optimized build
        version=$(awk 'BEGIN { FS=":"; RS="," } $1 ~ /"version"/ { gsub(/( |")/, "", $0); print $2 }' package.json)
        sed -i '/^<head>$/ a\    <meta name="application-name" content="hokiegeek.net_tea" data-version="'${version}${version_suffix:+":${version_suffix}"}'" />' dist/index.html
        head dist/index.html
    - test: |
        apk update && apk upgrade
        echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories
        echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories
        apk add --no-cache chromium@edge harfbuzz@edge nss@edge
        npm run test
