image: alpine/edge
packages:
  - nodejs
  - npm
  - chromium
  - harfbuzz
  - nss
  - docker
  - shadow
  - ansible
# - python
sources:
  - https://git.sr.ht/~hokiegeek/hg-tea
environment:
  PROJ: hg-tea
  GIT_TAG: $(git --work-tree=./hg-tea --git-dir=./hg-tea/.git describe)
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  CHROME_BIN: "/usr/bin/chromium-browser"
  CI_REGISTRY: quay.io
  CI_REGISTRY_USER: hokiegeek
  SERVICE: hgtea.service
  ADMIN_USER: hokiegeek
  DEPLOY_HOST: hokiegeek.net
secrets:
  - d675b280-e56b-4c0f-9908-549c70a7e2f9
  - d036fc7d-4eb9-4589-9d37-f61214d4fcb3
tasks:
  - setup: |
      sudo mount -t tmpfs -o size=4G /dev/null /dev/shm
      sudo service cgroups start
      sleep 2
      sudo nohup dockerd --bip 172.18.0.1/16 </dev/null >/dev/null 2>&1 &
      sleep 5
      sudo usermod -aG docker $(whoami)
  - install: |
      cd ${PROJ}
      npm install
  - lint: |
      cd ${PROJ}
      npm run lint
  - build: |
      cd ${PROJ}
      npm run build
      version=$(awk 'BEGIN { FS=":"; RS="," } $1 ~ /"version"/ { gsub(/( |")/, "", $0); print $2 }' package.json)
      sed -i '/^<head>$/ a\    <meta name="application-name" content="hokiegeek.net_tea" data-version="'${version}${version_suffix:+":${version_suffix}"}'" />' dist/index.html
  - test: |
      cd ${PROJ}
      npm run test
  - package: |
      cd ${PROJ}
      IMAGE=${CI_REGISTRY}/hokiegeek/hg-tea
      IMAGE_TAG=${IMAGE}:${GIT_TAG}
      IMAGE_LATEST_TAG=${IMAGE}:latest
      docker build -t $IMAGE_TAG .
      docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
      cat $HOME/.image_registry_token | docker login -u ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      docker push $IMAGE_TAG
      docker push $IMAGE_LATEST_TAG
  - deploy: |
      cd ${PROJ}
      ansible-playbook -i ${DEPLOY_HOST}, -u ${ADMIN_USER} -e image=${CI_REGISTRY}/hokiegeek/hg-tea:latest ./prod-conf/ansible.yml
