image: alpine/edge
packages:
  - nodejs
  - npm
  - chromium
  - harfbuzz
  - nss
sources:
  - https://git.sr.ht/~hokiegeek/hg-tea
environment:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
  CHROME_BIN: "/usr/bin/chromium-browser"
tasks:
  - setup: |
      cd hg-tea
      npm install
  - lint: |
      cd hg-tea
      npm run lint
  - build: |
      cd hg-tea
      npm run build
      version=$(awk 'BEGIN { FS=":"; RS="," } $1 ~ /"version"/ { gsub(/( |")/, "", $0); print $2 }' package.json)
      sed -i '/^<head>$/ a\    <meta name="application-name" content="hokiegeek.net_tea" data-version="'${version}${version_suffix:+":${version_suffix}"}'" />' dist/index.html
  - test: |
      cd hg-tea
      npm run test
