image: node:6

stages:
    - build
    - test
    - deploy

before_script:
  - npm install

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:0.5.0
  IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest

cache:
  paths:
    - node_modules/
    - dist/

build-app:
  stage: build
  script:
    - npm run build

      # lint:
      #   stage: build
      #   script:
      #     - npm run lint

      # node:6:
      #   stage: test
      #   script:
      #     - npm install -g codecov
      #     - npm test && codecov
      # 
      # node:7:
      #   stage: test
      #   image: node:7
      #   script:
      #     - npm test
      # 
      # node:4:
      #   stage: test
      #   image: node:4
      #   script:
      #     - npm test

build-docker:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
