image: node:6

stages:
    - build
    - test
    - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - dist/

build:app:
  script:
    - npm run build

build:lint:
  script:
    - npm run lint

test:node:6:
  script:
    - npm run testci

test:node:7:
  image: node:7
  script:
    - npm run testci

deploy:container:
  image: docker:git
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:0.5.0
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
