image: node:10

stages:
    - build
    - test
    - release

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - dist/

build-app:
  stage: build
  script:
    - npm run build

lint:
  stage: build
  script:
    - npm run lint
  only:
    - tags

lint-warn:
  stage: build
  script:
    - npm run lint
  except:
    - tags
  allow_failure: true

unit-node:8:
  stage: test
  image: node:8
  script:
    - npm run test

unit-node:9:
  stage: test
  image: node:9-alpine
  variables:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
  before_script:
    - apk update && apk upgrade && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/community >> /etc/apk/repositories && \
      echo @edge http://nl.alpinelinux.org/alpine/edge/main >> /etc/apk/repositories && \
      apk add --no-cache \
      chromium@edge \
      nss@edge
  script:
    - npm run test

unit-node:10:
  stage: test
  script:
    - npm run test

unit-node:latest:
  stage: test
  image: node:latest
  script:
    - npm run test
  allow_failure: true

.e2e-node:9:
  stage: test
  script:
    - npm run e2e
  allow_failure: true

create-dev-container:
  stage: release
  image: docker:git
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:SNAPSHOT
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  except:
    - tags

create-container:
  stage: release
  image: docker:git
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - tags
  except:
    - branches

.build-evaluate:
  stage: test
  image: registry.gitlab.com/hokiegeek/nexus-lifecycle-gitlab:latest
  variables:
    IQ_APPID: subdomain1
  script:
    - evaluate
  after_script:
    - gitlab
  only:
    - tags
  allow_failure: true

.restart-dev-service:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - curl "http://hokiegeek.net:8081/ServiceRestart?id=$SERVICE_RESTARTER_ID&service=hgtea-dev.service"
  only:
    - branches

.restart-service:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - curl "http://hokiegeek.net:8081/ServiceRestart?id=$SERVICE_RESTARTER_ID&service=hgtea.service"
  only:
    - tags
