image: node:9

stages:
    - build
    - test
    - release

before_script:
  - npm install

cache:
  paths:
    - node_modules/
    - dist/

build-app:
  stage: build
  script:
    - npm run build

lint:
  stage: build
  script:
    - npm run lint
  only:
    - master

lint-warn:
  stage: build
  script:
    - npm run lint
  except:
    - master
  allow_failure: true

unit-node:6:
  stage: test
  image: node:6
  script:
    - npm run test

unit-node:7:
  stage: test
  image: node:7
  script:
    - npm run test

unit-node:8:
  stage: test
  image: node:8
  script:
    - npm run test

unit-node:9:
  stage: test
  script:
    - npm run test

unit-node:latest:
  stage: test
  image: node:latest
  script:
    - npm run test
  allow_failure: true

      # e2e-node:9:
      #   stage: test
      #   script:
      #     - npm run e2e
      #   allow_failure: true

create-container:
  stage: release
  image: docker:git
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:SNAPSHOT
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - branches

create-container:
  stage: release
  image: docker:git
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    IMAGE_LATEST_TAG: $CI_REGISTRY_IMAGE:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker tag $IMAGE_TAG $IMAGE_LATEST_TAG
    - docker push $IMAGE_TAG
    - docker push $IMAGE_LATEST_TAG
  only:
    - tags
    
.build-evaluate:
  stage: test
  image: registry.gitlab.com/hokiegeek/nexus-lifecycle-gitlab:latest
  variables:
    IQ_APPID: subdomain1
  script:
    - evaluate
  after_script:
    - gitlab
  only:
    - tags
  allow_failure: true

